import streamlit as st

st.set_page_config(
    page_title="Help & FAQ",
    page_icon="❓",
)

st.title("❓ Help & FAQ")
st.markdown("Find answers to common questions about the Student Recommendation System.")

st.header("How to Use the App")
with st.expander("1. How do I get recommendations?"):
    st.markdown("""
    1.  **Sign Up/Login:** You must create an account or log in to access the recommender.
    2.  **Navigate:** Go to the "Recommender" page from the sidebar or the dashboard.
    3.  **Fill the Form:** Provide your academic and personal details in the form.
    4.  **Submit:** Click the "Get Recommendations" button. You will be automatically taken to the results page.
    """)

with st.expander("2. How do I update my profile?"):
    st.markdown("""
    Navigate to the "Settings" page from the sidebar. There you can update your first and last name.
    """)

with st.expander("3. How do I log out?"):
    st.markdown("""
    You can log out from the "Settings" page. Clicking the "Logout" button will end your session and return you to the login screen.
    """)

st.header("Understanding the Recommendations")
with st.expander("What does 'Estimated Grade' mean?"):
    st.markdown("""
    The 'Estimated Grade' is a prediction of your likely academic performance classification (e.g., 'A', 'B', 'C') based on the data you provided. It is generated by a machine learning model and should be considered an estimate, not a guarantee.
    """)

with st.expander("How are the 'Recommended Courses' chosen?"):
    st.markdown("""
    The recommended courses are suggestions based on your profile. The goal is to suggest courses that students with similar profiles have succeeded in.
    """)

st.header("Troubleshooting")
with st.expander("I can't log in."):
    st.markdown("""
    Please double-check that you are using the correct email and password. If you have forgotten your password, a password reset feature is not yet implemented. Please create a new account for now.
    """)

with st.expander("The app is not loading correctly."):
    st.markdown("""
    Try clearing your browser's cache and refreshing the page. If the problem persists, please contact us using the information on the "About" page.
    """)
